engines:
  eslint:
    enabled: true
    channel: 'eslint-9'
    config:
      config: 'eslint.config.mjs'

checks:
  return-statements:
    enabled: false
  similar-code:
    enabled: false
  method-lines:
    config:
      threshold: 50
  method-complexity:
    config:
      threshold: 20
  file-lines:
    config:
      threshold: 900

ratings:
  paths:
    - '**.js'
