name: Haraka Lint

on: [ push, pull_request ]

jobs:

  lint:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
    - uses: actions/checkout@v2
      name: Checkout
      with:
        fetch-depth: 1

    - uses: actions/setup-node@v2
      name: Use Node.js ${{ matrix.node-version }}
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install
      run: npm install

    - name: Lint
      run: npm run lint

      env:
        CI: true